_target_: src.models.fis_resnet_v1.FISResNet
seed: ${train.seed}
model_mode: l2
resnet_mode: resnet20
tree_type: random
data_name: cifar10
pool_mode: max
semiring: maxplus
maxplus_linear: false
use_valuation: false
maxplus_normalization: false
num_nodes: 3