_target_: src.models.tiny_fashion_net.TinyFashionNetPureFIS
ch1: 1
ch2: 4
ch3: 8
p_drop: 0.0
use_skip_connections: false
skip_connections_gamma: null # None for no gamma, float for gamma init value
maxplus_linear: false
use_valuation: false
maxplus_normalization: false
semiring: maxplus
use_discounted_sums: false
discount_init: -0.01
use_positional_encoding: false
pe_type: sinusoidal_2d
pe_kwargs: null
num_nodes: 2
fis1_seed: 0
fis2_seed: 3
sums_internal_activation: null # None for no activation, 'zero' for debugging, 'relu' for standard activation, ...
pool_mode: max # "max" or "avg"