_target_: src.models.tiny_fashion_net.TinyFashionNetFIS
ch1: 32
ch2: 64
ch3: 128
p_drop: 0.0
use_skip_connections: false
maxplus_linear: false
use_valuation: false
maxplus_normalization: false
semiring: maxplus
use_discounted_sums: false
discount_init: 0.99
use_positional_encoding: false
pe_type: sinusoidal_2d
pe_kwargs: null
num_nodes: 2
fis1_seed: 0
fis2_seed: 3