rich_model_summary:
  # _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: 2

rich_progress_bar:
  # _target_: lightning.pytorch.callbacks.RichProgressBar
  refresh_rate_per_second: 1.0
